# Site settings
permalink: /:categories/:title.html
title: 永超
email: putaoteng@hotmail.com
keywords: 永超,安卓开发,安卓经验分享,web开发,前端开发
description: 永超是特尼的个人独立博客，内容包括web前端开发和安卓app开发经验分享。
baseurl: ""
url: http://yongchao.net
twitter_username: teni
github_username:  teni

# Build settings
markdown: kramdown
