# Site settings
permalink: /:categories/:title.html
title: 葡萄藤
email: putaoteng@hotmail.com
description: 葡萄藤
baseurl: ""
url: 
twitter_username: teni
github_username:  teni

# Build settings
markdown: kramdown
