# Site settings
permalink: /:categories/:title.html
title: 葡萄藤
email: putaoteng@hotmail.com
keywords: 葡萄藤,安卓开发,安卓经验分享,web开发,前端开发
description: 葡萄藤是特尼的个人独立博客，内容包括web前端开发和安卓app开发经验分享。
baseurl: ""
url: 
twitter_username: teni
github_username:  teni

# Build settings
markdown: kramdown
